let lista1 = [1,2,3,4]
let lista2 = [1,2,3,4]

console.log(lista1[0]+lista2[0])
console.log(lista1[1]+lista2[1])
console.log(lista1[2]+ lista2[2])
console.log(lista1[3]+lista2[3])

let valores = [1,3,`cincum?`,8,9,`dez`,11,`doze`,13]
valores [2] = 5
valores [5] = 10
valores [7] = 12
console.log(valores[2],valores[5],valores[7])

let listao = []
listao.push(5)
listao.push(4)
listao.push(3)
listao.push(2)
listao.push(1)
console.log(listao)
function Numeros () {
    
    let maior = listao[0]
    let menor = listao[0]
    let totalMaior1 = 0
    let totalMaior2 = 0
    for (let i in listao,i++) {
        if (listao > maior  ) {
            maior = listao
        }

    }
}